### ISSUE TITLE
请教一下作者，想在一个model对两个字段进行索引

### ISSUE THREAD

**Issue by memorycancel** [huacnlee/redis-search#46]
1.如题，请教下作者，项目用到贵gem，在一个model对两个字段进行索引，在new一个model时，只会对一个字段进行索引，该如何进行扩展啊？或者思路?

例如：

 class Person < ActiveRecord::Base
 redis_search_index(title_field: :name_cn,
                     prefix_index_enable: false,
                     ext_fields: [ :name_en, :age])

  redis_search_index(title_field: :name_en,
                     prefix_index_enable: false,
                     ext_fields: [ :name_cn, :age])
end

2.update问题。在修改添加过索引的model字段时，貌似会报错。error: segmentation fault

**Comment by memorycancel** [comment]
在线等。急～～～

**Comment by huacnlee** [comment]
1. 做一个虚拟的字段

```
class User
  redis_search_index(title_field: :fullname)
  def fullname
    [name, name_en].join(' ')
  end
end
```

2. segmentation fault 具体错误信息是什么

**Comment by memorycancel** [comment]
@huacnlee , 多谢回复。按照你的思路第一个问题解决了。
第二个问题不是gem包的原因，已经解决。
