### ISSUE TITLE
执行 rake redis_search:index DIR=app/models 报错

### ISSUE THREAD

**Issue by gallifreyer** [huacnlee/redis-search#48]
执行` rake redis_search:index DIR=app/models `报错
`NoMethodError: undefined method `load_dictionaries' for RMMSeg::Dictionary:Module`

**Comment by huacnlee** [comment]
什么版本，rmmseg 已经被去掉了

**Comment by huacnlee** [comment]
请给出详细错误

**Comment by gallifreyer** [comment]
gemfile.lock
`
redis-search (0.9.7)
      redis (>= 3.0.0)
      redis-namespace (>= 1.3.0)
      ruby-pinyin (~> 0.3, >= 0.3.0)
 rmmseg-cpp-new (0.3.1)
      ruby-pinyin (0.5.0)
      rmmseg-cpp-new (~> 0.3.1)
`

详细错误信息:
`rake redis_search:index DIR=app/models' --trace
** Invoke redis_search:index:model (first_time)
** Invoke environment (first_time)
** Execute environment
rake aborted!
NoMethodError: undefined method `load_dictionaries' for RMMSeg::Dictionary:Module
/Users/tardis/.rvm/gems/ruby-2.2.3@tardis/gems/redis-search-0.9.7/lib/redis/search/config.rb:13:in `configure'
/Users/tardis/Projects/cross-hire/config/initializers/redis-search.rb:11:in `<top (required)>'
/Users/tardis/.rvm/gems/ruby-2.2.3@tardis/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:268:in `load'
/Users/tardis/.rvm/gems/ruby-2.2.3@tardis/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:268:in `block in load'
/Users/tardis/.rvm/gems/ruby-2.2.3@tardis/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:240:in `load_dependency'
/Users/tardis/.rvm/gems/ruby-2.2.3@tardis/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:268:in `load'
/Users/tardis/.rvm/gems/ruby-2.2.3@tardis/gems/railties-4.2.4/lib/rails/engine.rb:652:in `block in load_config_initializer'
/Users/tardis/.rvm/gems/ruby-2.2.3@tardis/gems/activesupport-4.2.4/lib/active_support/notifications.rb:166:in `instrument'
/Users/tardis/.rvm/gems/ruby-2.2.3@tardis/gems/railties-4.2.4/lib/rails/engine.rb:651:in `load_config_initializer'
/Users/tardis/.rvm/gems/ruby-2.2.3@tardis/gems/railties-4.2.4/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'
/Users/tardis/.rvm/gems/ruby-2.2.3@tardis/gems/railties-4.2.4/lib/rails/engine.rb:615:in `each'
/Users/tardis/.rvm/gems/ruby-2.2.3@tardis/gems/railties-4.2.4/lib/rails/engine.rb:615:in `block in <class:Engine>'
/Users/tardis/.rvm/gems/ruby-2.2.3@tardis/gems/railties-4.2.4/lib/rails/initializable.rb:30:in `instance_exec'
/Users/tardis/.rvm/gems/ruby-2.2.3@tardis/gems/railties-4.2.4/lib/rails/initializable.rb:30:in `run'
/Users/tardis/.rvm/gems/ruby-2.2.3@tardis/gems/railties-4.2.4/lib/rails/initializable.rb:55:in `block in run_initializers'
/Users/tardis/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/tsort.rb:226:in `block in tsort_each'
/Users/tardis/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
/Users/tardis/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/tsort.rb:420:in `block (2 levels) in each_strongly_connected_component_from'
/Users/tardis/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/tsort.rb:429:in `each_strongly_connected_component_from'
/Users/tardis/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/tsort.rb:419:in `block in each_strongly_connected_component_from'
/Users/tardis/.rvm/gems/ruby-2.2.3@tardis/gems/railties-4.2.4/lib/rails/initializable.rb:44:in `each'
/Users/tardis/.rvm/gems/ruby-2.2.3@tardis/gems/railties-4.2.4/lib/rails/initializable.rb:44:in `tsort_each_child'
/Users/tardis/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/tsort.rb:413:in `call'
/Users/tardis/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/tsort.rb:413:in `each_strongly_connected_component_from'
/Users/tardis/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/tsort.rb:347:in `block in each_strongly_connected_component'
/Users/tardis/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/tsort.rb:345:in `each'
/Users/tardis/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/tsort.rb:345:in `call'
/Users/tardis/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/tsort.rb:345:in `each_strongly_connected_component'
/Users/tardis/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/tsort.rb:224:in `tsort_each'
/Users/tardis/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/tsort.rb:203:in `tsort_each'
/Users/tardis/.rvm/gems/ruby-2.2.3@tardis/gems/railties-4.2.4/lib/rails/initializable.rb:54:in `run_initializers'
/Users/tardis/.rvm/gems/ruby-2.2.3@tardis/gems/railties-4.2.4/lib/rails/application.rb:352:in `initialize!'
/Users/tardis/Projects/cross-hire/config/environment.rb:5:in `<top (required)>'
/Users/tardis/.rvm/gems/ruby-2.2.3@tardis/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
/Users/tardis/.rvm/gems/ruby-2.2.3@tardis/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `block in require'
/Users/tardis/.rvm/gems/ruby-2.2.3@tardis/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:240:in `load_dependency'
/Users/tardis/.rvm/gems/ruby-2.2.3@tardis/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
/Users/tardis/.rvm/gems/ruby-2.2.3@tardis/gems/railties-4.2.4/lib/rails/application.rb:328:in `require_environment!'
/Users/tardis/.rvm/gems/ruby-2.2.3@tardis/gems/railties-4.2.4/lib/rails/application.rb:457:in `block in run_tasks_blocks'
/Users/tardis/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/task.rb:240:in `call'
/Users/tardis/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/task.rb:240:in `block in execute'
/Users/tardis/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/task.rb:235:in `each'
/Users/tardis/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/task.rb:235:in `execute'
/Users/tardis/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/task.rb:179:in `block in invoke_with_call_chain'
/Users/tardis/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/Users/tardis/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/task.rb:172:in `invoke_with_call_chain'
/Users/tardis/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/task.rb:201:in `block in invoke_prerequisites'
/Users/tardis/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/task.rb:199:in `each'
/Users/tardis/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/task.rb:199:in `invoke_prerequisites'
/Users/tardis/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/task.rb:178:in `block in invoke_with_call_chain'
/Users/tardis/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/Users/tardis/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/task.rb:172:in `invoke_with_call_chain'
/Users/tardis/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/task.rb:165:in `invoke'
/Users/tardis/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/application.rb:150:in `invoke_task'
/Users/tardis/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/application.rb:106:in `block (2 levels) in top_level'
/Users/tardis/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/application.rb:106:in `each'
/Users/tardis/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/application.rb:106:in `block in top_level'
/Users/tardis/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/application.rb:115:in `run_with_threads'
/Users/tardis/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/application.rb:100:in `top_level'
/Users/tardis/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/application.rb:78:in `block in run'
/Users/tardis/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/application.rb:176:in `standard_exception_handling'
/Users/tardis/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/application.rb:75:in `run'
bin/rake:4:in `<main>'
Tasks: TOP => redis_search:index:model => environment`

**Comment by huacnlee** [comment]
用低版本的 ruby-pinyin ，例如 0.3.x
或用 redis-search 1.0.0.beta2

**Comment by gallifreyer** [comment]
@huacnlee   用了低版本的ruby-pinyin, 问题已解决, 多谢帮助~~~

但是也试了一下用 redis-search 1.0.0.beta2，没有成功， 错误信息是
```
rake redis_search:index:model CLASS='EducationExperience' --trace
rake aborted!
Bundler::GemRequireError: There was an error while trying to load the gem 'redis-search'.
/Users/tardis/.rvm/gems/ruby-2.2.3@tardis/gems/bundler-1.11.2/lib/bundler/runtime.rb:80:in `rescue in block (2 levels) in require'
/Users/tardis/.rvm/gems/ruby-2.2.3@tardis/gems/bundler-1.11.2/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
/Users/tardis/.rvm/gems/ruby-2.2.3@tardis/gems/bundler-1.11.2/lib/bundler/runtime.rb:72:in `each'
/Users/tardis/.rvm/gems/ruby-2.2.3@tardis/gems/bundler-1.11.2/lib/bundler/runtime.rb:72:in `block in require'
/Users/tardis/.rvm/gems/ruby-2.2.3@tardis/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in `each'
/Users/tardis/.rvm/gems/ruby-2.2.3@tardis/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in `require'
/Users/tardis/.rvm/gems/ruby-2.2.3@tardis/gems/bundler-1.11.2/lib/bundler.rb:99:in `require'
/Users/tardis/Projects/cross-hire/config/application.rb:7:in `<top (required)>'
/Users/tardis/Projects/cross-hire/Rakefile:4:in `require'
/Users/tardis/Projects/cross-hire/Rakefile:4:in `<top (required)>'
/Users/tardis/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/rake_module.rb:28:in `load'
/Users/tardis/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/rake_module.rb:28:in `load_rakefile'
/Users/tardis/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/application.rb:689:in `raw_load_rakefile'
/Users/tardis/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/application.rb:94:in `block in load_rakefile'
/Users/tardis/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/application.rb:176:in `standard_exception_handling'
/Users/tardis/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/application.rb:93:in `load_rakefile'
/Users/tardis/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/application.rb:77:in `block in run'
/Users/tardis/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/application.rb:176:in `standard_exception_handling'
/Users/tardis/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/application.rb:75:in `run'
bin/rake:4:in `<main>'
NameError: uninitialized constant Redis::ActiveSupport::Concern
/Users/tardis/.rvm/gems/ruby-2.2.3@tardis/gems/redis-search-1.0.0.beta2/lib/redis-search/base.rb:6:in `<module:Search>'
/Users/tardis/.rvm/gems/ruby-2.2.3@tardis/gems/redis-search-1.0.0.beta2/lib/redis-search/base.rb:3:in `<class:Redis>'
/Users/tardis/.rvm/gems/ruby-2.2.3@tardis/gems/redis-search-1.0.0.beta2/lib/redis-search/base.rb:1:in `<top (required)>'
/Users/tardis/.rvm/gems/ruby-2.2.3@tardis/gems/redis-search-1.0.0.beta2/lib/redis-search.rb:1:in `<top (required)>'
/Users/tardis/.rvm/gems/ruby-2.2.3@tardis/gems/bundler-1.11.2/lib/bundler/runtime.rb:77:in `require'
/Users/tardis/.rvm/gems/ruby-2.2.3@tardis/gems/bundler-1.11.2/lib/bundler/runtime.rb:77:in `block (2 levels) in require'
/Users/tardis/.rvm/gems/ruby-2.2.3@tardis/gems/bundler-1.11.2/lib/bundler/runtime.rb:72:in `each'
/Users/tardis/.rvm/gems/ruby-2.2.3@tardis/gems/bundler-1.11.2/lib/bundler/runtime.rb:72:in `block in require'
/Users/tardis/.rvm/gems/ruby-2.2.3@tardis/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in `each'
/Users/tardis/.rvm/gems/ruby-2.2.3@tardis/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in `require'
/Users/tardis/.rvm/gems/ruby-2.2.3@tardis/gems/bundler-1.11.2/lib/bundler.rb:99:in `require'
/Users/tardis/Projects/cross-hire/config/application.rb:7:in `<top (required)>'
/Users/tardis/Projects/cross-hire/Rakefile:4:in `require'
/Users/tardis/Projects/cross-hire/Rakefile:4:in `<top (required)>'
/Users/tardis/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/rake_module.rb:28:in `load'
/Users/tardis/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/rake_module.rb:28:in `load_rakefile'
/Users/tardis/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/application.rb:689:in `raw_load_rakefile'
/Users/tardis/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/application.rb:94:in `block in load_rakefile'
/Users/tardis/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/application.rb:176:in `standard_exception_handling'
/Users/tardis/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/application.rb:93:in `load_rakefile'
/Users/tardis/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/application.rb:77:in `block in run'
/Users/tardis/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/application.rb:176:in `standard_exception_handling'
/Users/tardis/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/application.rb:75:in `run'
bin/rake:4:in `<main>'
```
