### ISSUE TITLE
task tIDENTIFIER

### ISSUE THREAD

**Issue by ysllyfe** [huacnlee/redis-search#50]
ERROR:
lib/redis-search/tasks.rb:35: syntax error, unexpected tIDENTIFIER, expecting ')'
      batch = ENV['BATCH'].to_i || 1000

and in lib/redis-search/tasks.rb line 34
klass = Object.const_get((ENV['CLASS'].to_s)

**Comment by huacnlee** [comment]
Oh, That's a mistake, version 1.0.1 has fixed.
